spring.application.name=nutrihealth

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.hibernate.ddl-auto=update

project.image=images

#Needed if you are using elastic beanstalk
server.port = 5000

spring.datasource.url=jdbc:postgresql://nutrihealth.c7k80e4wkmei.ap-southeast-2.rds.amazonaws.com:5432/nutrihealth
spring.datasource.username=postgres
spring.datasource.password=rachitabhishek

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.security.user.password =Test@123
spring.security.user.name=test

spring.app.jwtSecret=${SPRING_APP_JWTSECRET:bXlTZWNyZXRLZXkxMjM5MTI3Mzhhb3BzZ2puc3BrbW5kZnNvcGt2YWpvaXJqZzk0Z2Yyb3BmbmcybW9rbm0=}
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootEcom

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecom.nutrihealth=DEBUG