spring.application.name=nutrihealth
project.image=images
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nutrihealth}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rachitabhishek}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.password=${SPRING_SECURITY_PASSWORD:Test@123}
spring.security.user.name=${SPRING_SECURITY_USERNAME:test}

spring.app.jwtSecret=${SPRING_APP_JWTSECRET:localSecretKeyForDevelopmentOnly123456}
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootEcom